openapi: 3.1.0

info:
  title: Shared OpenAPI components
  version: "1.0"
  description: For this example we use it locally instead of remotely (https://some.server/library.openapi.yaml#/components/...)

components:
  parameters:
    Pagination: # Check section 16.3.3 of The Design of Web APIs
      name: pagination 
      description: Pagination parameters (`.../?next=s00999&limit=10`)
      in: query
      schema:
        type: 
          properties:
            next:
              description: Next page cursor
              type: string
            limit:
              description: Number of elements per page
              type: number
  responses:
    Error500:
      description: Unexpected error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
  schemas:
    Error:
      type: object