openapi: 3.1.0

info:
  title: Shopping
  version: "1.0"

paths:
  /products:
    get: 
      parameters:
        # 🚨 buyPRice instead of buyPrice
        - name: buyPRice
          in: query
          schema:
            type: number
        # ✅ camelCased name
        - name: supplierReference
          in: query
          schema:
            type: number
      responses:
        "200":
          description: Found products