openapi: 3.1.0

info:
  title: Shared OpenAPI components
  version: "1.0"
  description: For this example we use it locally instead of remotely (https://some.server/library.openapi.yaml#/components/...)

components:
  parameters:
    CorrelationId:
      name: Correlation-Id
      in: header
      schema:
        type: string
  responses:
    Error500:
      description: Unexpected error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
  schemas:
    Error:
      type: object