openapi: 3.1.0

info: 
  title: File storage
  version: "1.0"

paths:
  /files/{fileId}:
    parameters:
      - name: fileId
        in: path
        required: true
        schema:
          type: string
    get:
      responses:
        "200":
          description: File content or metadata
          content:
            application/pdf: {} # Raw file data
            image/png: {}       # Raw file data
            image/jpeg: {}      # Raw file data
            application/json: # File metadata
              schema:
                type: object
                properties:
                  name:
                    type: string
                  size:
                    type: integer
                  created:
                    type: string
                  updated:
                    type: string