openapi: 3.1.0

info:
  title: Banking
  version: "1.0"

paths:
  /transfers:
    # ✅ Path-level parameters list without Correlation-Id header
    parameters:
      - name: Correlation-Id
        in: header
        schema:
          type: string
    post:
      responses:
        "201":
          description: Money transfered
        # ✅ 500 defined
        "500":
          description: Unexpected error
  /accounts:
    # 🚨 No path-level parameters list
    get:
      responses:
        "200":
          description: Found accounts
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
        # 🚨 No 500 defined
  /accounts/{accountId}:
    # 🚨 Path-level parameters list without Correlation-Id header
    parameters:
      - name: accountId
        in: path
        required: true
        schema:
          type: string
    get:
      responses:
        "200":
          description: An account
        # ✅ 500 defined
        "500":
          description: Unexpected error

components:
  schemas:
    Account:
      type: object
      # ✅ filled required list
      required: [id]
      properties:
        id:
          type: string
    Transaction:
      type: object
      # 🚨 no required list 
      properties:
        id: 
          type: string
    TransactionPatch:
      type: object
      # ✅ empty required list
      required: []
      properties:
        tags:
          type: array
          items:
            type: string