openapi: 3.1.0

info: 
  title: Document Management
  version: "1.0"
  
paths:
  /files:
    post:
      requestBody:
        content:
          application/octet-stream: {}
      responses:
        "201":
          description: File stored.
          content:
            application/json:
              schema:
                type: integer
                description: The ID of the created document.