openapi: 3.1.0

info:
  title: Banking
  version: "1.0"

paths:

  /owners:
    get:
      responses:
        "200":
          description: Found accounts

  /accounts:
    get:
      parameters:
        - name: q
          in: header
          schema:
            type: string
      responses:
        "200":
          description: Found accounts


  /transactions:
    get:
      parameters:
        - name: q
          in: query
          schema:
            type: number
      responses:
        "200":
          description: Found transactions

components:
  schemas:
    TransactionCreate:
      properties:
        Amount:
          type: number