openapi: 3.1.0

info:
  title: Online Shopping
  version: "1.0"

paths: {}

components: # Where to define reusable elements 
  schemas: # Map of reusable JSON schemas
    Product:
      type: object
      properties: {} # A map of JSON schemas describing the object's properties