openapi: 3.1.0

info:
  title: Online Shopping
  version: "1.0"

paths:
  /products:
    get:
      summary: Search for products
      parameters: # Operation-level parameters list
        - name: keywords
          in: query
          style: form # Controls object or array serialization
          explode: false # Controls object or array serialization
          schema:
            type: array # The parameter's inline schema is copied and pasted from the corresponding property of the Product reusable schema
            items: # The parameter's inline schema is copied and pasted from the corresponding property of the Product reusable schema
              type: string # The parameter's inline schema is copied and pasted from the corresponding property of the Product reusable schema
components:
  schemas:
    Product:
      properties:
        keywords:
          type: array # The parameter's inline schema is copied and pasted from the corresponding property of the Product reusable schema
          items: # The parameter's inline schema is copied and pasted from the corresponding property of the Product reusable schema
            type: string # The parameter's inline schema is copied and pasted from the corresponding property of the Product reusable schema