openapi: 3.1.0

info:
  title: Online Shopping
  version: "1.0"

paths:
  /products:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductCreationOrReplacement" # A reference to the ProductCreationOfReplacement schema located under components.schemas
      responses:
        "201":
          description: Product added to the catalog
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product" # A reference to the Product schema located under components.schemas
    get:
      responses:
        "200":
          description: List of products
          content:
            application/json:
              schema:
                type: array # An inline array schema
                items: # The array elements schema is a reference to the ProductSummary reusable schema
                  $ref: "#/components/schemas/ProductSummary" # The array elements schema is a reference to the ProductSummary reusable schema

  /products/{productReference}:
    parameters:
      - name: productReference
        in: path
        required: true
        schema:
          type: string
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductCreationOrReplacement" # A reference to the ProductCreationOfReplacement schema located under components.schemas
      responses: 
        "200":
          description: Updated product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product" # A reference to the Product schema located under components.schemas
  
components: 
  schemas:
    Product:
      type: object
      required:
        - productReference
        - name
        - category
        - price
        - dateAdded
      properties:
        productReference: 
          type: integer
          description: Unique identifier
        name:
          type: string
        description:
          type: string
        keywords:
          type: array 
          items:
            type: string 
        category:
          type: string
        price:
          type: number
          description: Price in USD
        dateAdded:
          type: string
          format: date
        isProductUnavailable:
          type: boolean
          description: Temporarily unavailable
        supplier: # Leverages a reference to another schema
          $ref: "#/components/schemas/SupplierSummary"      

    SupplierSummary: # The targeted schema
      type: object
      required:
        - supplierCode
        - name
      properties:
        supplierCode:
          type: string
          description: Unique identifier
        name:
          type: string      

    ProductCreationOrReplacement:  
      type: object
      required: 
        - name
        - category
        - price
        - supplier
      properties:
        name:
          type: string
        description:
          type: string
        keywords:
          type: array 
          items:
            type: string
        category:
          type: string
        price:
          type: number
          description: Price in USD
        isProductUnavailable:
          type: boolean
          description: Temporarily unavailable
        supplier:
          type: object
          required:
            - supplierCode
          properties:
            supplierCode:
              type: string
              description: Unique identifier

    ProductSummary:
      type: object
      required: 
        - productReference
        - name
        - category
        - price
      properties:
        productReference: 
          type: integer
          description: Unique identifier
        name:
          type: string
        description:
          type: string  
        category:
          type: string
        price:
          type: number
          description: Price in USD