openapi: 3.1.0
info:
  title: Banking
  version: "1.0"
paths:
  /cards/search:
    post:
      responses:
        "200":
          description: Found cards
  /owners/search:
    post:
      parameters:
        - name: name
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Found owners
  /customers/search:
    parameters:
      - name: name
        in: query
        schema:
          type: string
    post:
      responses:
        "200":
          description: Found owners