openapi: 3.1.0

info:
  title: Online Shopping
  version: "1.0"

paths:
  /products:
    summary: Catalog
    post:
      summary: Add a product to the catalog
    get:
      summary: Search for products
  /products/{productReference}:
    summary: Product
    parameters: 
      - name: productReference
        in: path
        required: true
        schema: {}
    get:
      summary: Get product details
    put:
      summary: Modify a product
    delete:
      summary: Remove a product from the catalog