openapi: 3.1.0

info:
  title: Online Shopping
  version: "1.0"

paths:
  /products:
    summary: Catalog
    post: # The operation's HTTP method
      summary: Add a product to the catalog # The operation's name