openapi: 3.1.0

info:
  title: Online Shopping
  version: "1.0"

paths:
  /products:
    summary: Catalog
    post:
      summary: Add a product to the catalog
      requestBody: # The operation's request body
        description: Product info # Request body's description
        content:
          application/json: # Body's media type
            schema: {} # Needed to make the body definition valid
      responses:
        "201":
          description: Product added to the catalog
          content: # Data to be returned on 201 Created
            application/json: # The response body's media type is JSON
              schema:
                description: Product info. # Data description
        "400":
          description: Wrong product information
          content: # Data to be returned on 400 Bad Request
            application/json: # The response body's media type is JSON
              schema:
                description: Error info.
        "500":
          description: Unexpected server error
          content: # Data to be returned on 500 Internal Server Error
            application/json: # The response body's media type is JSON
              schema:
                description: Error info.