name: pagination
description: |
  Pagination parameters (`.../?next=s00999&limit=10`)
in: query
schema:
  type: object # Set type to object to create a group
  properties: # Each property is serialized as a query parameter
    next:
      description: Next page cursor
      type: string
    limit:
      description: Number of elements per page
      type: number