openapi: 3.1.0
info:
  title: Shared components
  version: "1.0" # The version of this OpenAPI file

# No paths or webhooks defined

components: # Components that can be used across APIs
  schemas:
    Error:
      required: 
        - message
      properties:
        message:
          type: string
  parameters:
    Pagination:
      name: pagination # Just shown in the documentation, not used in the request
      description: | # Better clarify how this parameter works 
        Pagination parameters (`.../?next=s00999&limit=10`)
      in: query
      schema:
        type: object # Set type to object to create a group
        properties: # Each property is serialized as a query parameter
          next:
            description: Next page cursor
            type: string
          limit:
            description: Number of elements per page
            type: number
  headers:
    ResourceLocation:
      description: Created resource URL
      schema:
        type: string
        format: uri
  responses:
    ResourceNotFound: # The reusable response identifier
      description: No resource was found
      content:
        'application/json':
          schema:
            $ref: '#/components/schemas/Error' # A reusable element may reference other reusable elements

