openapi: 3.1.0
info:
  title: Online Library
  version: "1.0"
paths:
  /authors:
    post:
      requestBody: 
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
      responses:
        "201":
          description: Author created.
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                  name:
                    type: string