openapi: 3.1.0

info:
  title: Online Shopping
  version: "1.0"

paths:
  /products/{ProductId}:
    parameters:
      - name: ProductId
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/Product/properties/id"
    get:
      responses:
        "200":
          description: Product details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product" # Same schema used in request and response
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product" # Same schema used in request and response
      responses: 
        "200":
          description: Product updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product" # Same schema used in request and response
components:
  schemas:
    Product:
      properties:
        id:
          readOnly: true # Will be used only on responses
          type: string
        price:
          type: number
        type:
          properties:
            code:
              writeOnly: true # Will be used only on requests
              type: string
            name:
              readOnly: true # Will be used only on responses
              type: string