openapi: 3.1.0

info:
  title: Banking
  version: "1.0"

paths:
  /accounts/{pathLevelPathParameter}:
    parameters:
      - name: pathLevelPathParameter
        in: path
        required: true
        schema:
          type: string
    get:
      responses:
        "200":
          description: An account
    put:
      responses:
        "200":
          description: Account modified
  /accounts:
    get:
      parameters:
        - name: operationLevelQueryParameter
          in: query
          schema: 
            type: string 
      responses:
        "200":
          description: Found accounts
    post:
      responses:
        "201":
          description: Account created
components:
  parameters:
    ReusablePathParameter:
      name: reusablePathParameter
      in: path
      required: true
      schema:
        type: string
    ReusableRequestHeader:
      name: Reusable-Request-Header
      in: header
      schema:
        type: string