extends:
  # should be https://guidelines.intra/guidelines.spectral.yaml 
  - ../guidelines-server/guidelines.spectral.yaml

rules:

  # Override rules coming from "extends"
  pagination: info
  vocabulary-experimental: true

  # Local rules

  bnkng-http-sig:
    severity: error
    given:
      - $.paths.*
    then:
      - field: parameters
        function: schema
        functionOptions:
          schema:
            type: array
            contains:
              const: "#/components/parameters/HttpSignature"

overrides: # Hides issues we won't fix
  - files:
      - "**/openapi.yaml#/paths/~1accounts/get"
    rules:
      search-q-defined: off
