openapi: 3.1.0

info:
  title: Banking
  version: "1.0"

paths:

  /accounts: 
    get: # doesn't define q filter, but "info" problem is ignored in .spectral.yaml with overrides
      responses:
        "200":
          description: Found accounts
